final members = {
  "aaron": {"picks_index": 3, "fav_team": "pit"},
  "alex": {"picks_index": 4, "fav_team": "bal"},
  "bruce": {"picks_index": 5},
  "chrissy": {"picks_index": 6},
  "cory": {"picks_index": 7},
  "dominique": {"picks_index": 8},
  "emma": {"picks_index": 9},
  "ethan": {"picks_index": 10, "fav_team": "ind"},
  "francois": {"picks_index": 11, "fav_team": "sea"},
  "graham": {"picks_index": 12},
  "janet": {"picks_index": 13, "fav_team": "hou"},
  "joy": {"picks_index": 14},
  "sara": {"picks_index": 15},
  "victoria": {"picks_index": 16},
};
