import 'dart:ui';

import 'package:cffp_web/api/models/divisions.dart';

final teams = {
  "ari": {
    "city": "Arizona",
    "division": Divisions.nfcWest,
    "name": "Cardinals",
    "primaryColor": const Color(0xff97233f),
    "onPrimaryColor": const Color(0xff000000),
    "secondaryColor": const Color(0xff000000),
    "logo": "assets/logos/arizona_cardinals.png",
  },
  "atl": {
    "city": "Atlanta",
    "division": Divisions.nfcSouth,
    "name": "Falcons",
    "primaryColor": const Color(0xffa71930),
    "onPrimaryColor": const Color(0xff000000),
    "secondaryColor": const Color(0xff000000),
    "tertiaryColor": const Color(0xffa5acaf),
    "logo": "assets/logos/atlanta_falcons.png",
  },
  "bal": {
    "city": "Baltimore",
    "division": Divisions.afcNorth,
    "name": "Ravens",
    "primaryColor": const Color(0xff241773),
    "onPrimaryColor": const Color(0xffffffff),
    "secondaryColor": const Color(0xff000000),
    "tertiaryColor": const Color(0xff9e7c0c),
    "logo": "assets/logos/baltimore_ravens.png",
  },
  "buf": {
    "city": "Buffalo",
    "division": Divisions.afcEast,
    "name": "Bills",
    "primaryColor": const Color(0xff00338d),
    "onPrimaryColor": const Color(0xffc60c30),
    "secondaryColor": const Color(0xffc60c30),
    "tertiaryColor": const Color(0xff00274d),
    "logo": "assets/logos/buffalo_bills.png",
  },
  "car": {
    "city": "Carolina",
    "division": Divisions.nfcSouth,
    "name": "Panthers",
    "primaryColor": const Color(0xff0085ca),
    "onPrimaryColor": const Color(0xff000000),
    "secondaryColor": const Color(0xff000000),
    "tertiaryColor": const Color(0xffbfc0bf),
    "logo": "assets/logos/carolina_panthers.png",
  },
  "chi": {
    "city": "Chicago",
    "division": Divisions.nfcNorth,
    "name": "Bears",
    "primaryColor": const Color(0xffc83803),
    "onPrimaryColo": const Color(0xff0b162a),
    "secondaryColor": const Color(0xff0b162a),
    "logo": "assets/logos/chicago_bears.png",
  },
  "cin": {
    "city": "Cincinnati",
    "division": Divisions.afcNorth,
    "name": "Bengals",
    "primaryColor": const Color(0xfffb4f14),
    "onPrimaryColor": const Color(0xff000000),
    "secondaryColor": const Color(0xff000000),
    "logo": "assets/logos/cincinnati_bengals.png",
  },
  "cle": {
    "city": "Cleveland",
    "division": Divisions.afcNorth,
    "name": "Browns",
    "primaryColor": const Color(0xff311d00),
    "onPrimaryColor": const Color(0xffff3c00),
    "secondaryColor": const Color(0xffff3c00),
    "logo": "assets/logos/cleveland_browns.png",
  },
  "dal": {
    "city": "Dallas",
    "division": Divisions.nfcEast,
    "name": "Cowboys",
    "primaryColor": const Color(0xff869397),
    "onPrimaryColor": const Color(0xff002244),
    "secondaryColor": const Color(0xff002244),
    "tertiaryColor": const Color(0xff00338d),
    "logo": "assets/logos/dallas_cowboys.png",
  },
  "den": {
    "city": "Denver",
    "division": Divisions.afcWest,
    "name": "Broncos",
    "primaryColor": const Color(0xfffb4f14),
    "onPrimaryColor": const Color(0xff002244),
    "secondaryColor": const Color(0xff002244),
    "logo": "assets/logos/denver_broncos.png",
  },
  "det": {
    "city": "Detroit",
    "division": Divisions.nfcNorth,
    "name": "Lions",
    "primaryColor": const Color(0xff0076b6),
    "onPrimaryColor": const Color(0xffb0b7bc),
    "secondaryColor": const Color(0xffb0b7bc),
    "logo": "assets/logos/detroit_lions.png",
  },
  "gb": {
    "city": "Green Bay",
    "division": Divisions.nfcNorth,
    "name": "Packers",
    "primaryColor": const Color(0xff203731),
    "onPrimaryColor": const Color(0xffffb612),
    "secondaryColor": const Color(0xffffb612),
    "logo": "assets/logos/green_bay_packers.png",
  },
  "hou": {
    "city": "Houston",
    "division": Divisions.afcSouth,
    "name": "Texans",
    "primaryColor": const Color(0xff03202f),
    "onPrimaryColor": const Color(0xffa71930),
    "secondaryColor": const Color(0xffa71930),
    "logo": "assets/logos/houston_texans.png",
  },
  "ind": {
    "city": "Indianapolis",
    "division": Divisions.afcSouth,
    "name": "Colts",
    "primaryColor": const Color(0xff002c5f),
    "onPrimaryColor": const Color(0xffa5acaf),
    "secondaryColor": const Color(0xffa5acaf),
    "logo": "assets/logos/indianapolis_colts.png",
  },
  "jax": {
    "city": "Jacksonville",
    "division": Divisions.afcSouth,
    "name": "Jaguars",
    "primaryColor": const Color(0xff006778),
    "onPrimaryColor": const Color(0xff9f792c),
    "secondaryColor": const Color(0xff9f792c),
    "tertiaryColor": const Color(0xff000000),
    "logo": "assets/logos/jacksonville_jaguars.png",
  },
  "kc": {
    "city": "Kansas City",
    "division": Divisions.afcWest,
    "name": "Chiefs",
    "primaryColor": const Color(0xffe31837),
    "onPrimaryColor": const Color(0xffffffff),
    "secondaryColor": const Color(0xffffb612),
    "tertiaryColor": const Color(0xffffffff),
    "logo": "assets/logos/kansas_city_chiefs.png",
  },
  "lac": {
    "city": "Los Angeles",
    "division": Divisions.afcWest,
    "name": "Chargers",
    "primaryColor": const Color(0xff0073cf),
    "onPrimaryColor": const Color(0xffffb612),
    "secondaryColor": const Color(0xffffb612),
    "tertiaryColor": const Color(0xff002244),
    "logo": "assets/logos/los_angeles_chargers.png",
  },
  "lar": {
    "city": "Los Angeles",
    "division": Divisions.nfcWest,
    "name": "Rams",
    "primaryColor": const Color(0xff003594),
    "onPrimaryColor": const Color(0xffffa300),
    "secondaryColor": const Color(0xffffa300),
    "logo": "assets/logos/los_angeles_rams.png",
  },
  "lv": {
    "city": "Las Vegas",
    "division": Divisions.afcWest,
    "name": "Raiders",
    "primaryColor": const Color(0xff000000),
    "onPrimaryColor": const Color(0xffa5acaf),
    "secondaryColor": const Color(0xffa5acaf),
    "logo": "assets/logos/las_vegas_raiders.png",
  },
  "mia": {
    "city": "Miami",
    "division": Divisions.afcEast,
    "name": "Dolphins",
    "primaryColor": const Color(0xff008e97),
    "onPrimaryColor": const Color(0xffffffff),
    "secondaryColor": const Color(0xfff26a24),
    "tertiaryColor": const Color(0xffffffff),
    "logo": "assets/logos/miami_dolphins.png",
  },
  "min": {
    "city": "Minnesota",
    "division": Divisions.nfcNorth,
    "name": "Vikings",
    "primaryColor": const Color(0xff4f2683),
    "onPrimaryColor": const Color(0xffffffff),
    "secondaryColor": const Color(0xffffc62f),
    "tertiaryColor": const Color(0xffffffff),
    "logo": "assets/logos/minnesota_vikings.png",
  },
  "ne": {
    "city": "New England",
    "division": Divisions.afcEast,
    "name": "Patriots",
    "primaryColor": const Color(0xff002244),
    "onPrimaryColor": const Color(0xffc60c30),
    "secondaryColor": const Color(0xffc60c30),
    "tertiaryColor": Color.fromRGBO(176, 183, 188, 1),
    "logo": "assets/logos/new_england_patriots.png",
  },
  "no": {
    "city": "New Orleans",
    "division": Divisions.nfcSouth,
    "name": "Saints",
    "primaryColor": const Color(0xffd3bc8d),
    "onPrimaryColor": const Color(0xff000000),
    "secondaryColor": const Color(0xff000000),
    "logo": "assets/logos/new_orleans_saints.png",
  },
  "nyg": {
    "city": "New York",
    "division": Divisions.nfcEast,
    "name": "Giants",
    "primaryColor": const Color(0xff0b2265),
    "onPrimaryColor": const Color(0xffa71930),
    "secondaryColor": const Color(0xffa71930),
    "tertiaryColor": const Color(0xffa5acaf),
    "logo": "assets/logos/new_york_giants.png",
  },
  "nyj": {
    "city": "New York",
    "division": Divisions.afcEast,
    "name": "Jets",
    "primaryColor": const Color(0xff003f2d),
    "onPrimaryColor": const Color(0xffffffff),
    "secondaryColor": const Color(0xffffffff),
    "logo": "assets/logos/new_york_jets.png",
  },
  "phi": {
    "city": "Philadelphia",
    "division": Divisions.nfcEast,
    "name": "Eagles",
    "primaryColor": const Color(0xff004c54),
    "onPrimaryColor": const Color(0xffa5acaf),
    "secondaryColor": const Color(0xffa5acaf),
    "tertiaryColor": const Color(0xff000000),
    "logo": "assets/logos/philedelphia_eagles.png",
  },
  "pit": {
    "city": "Pittsburgh",
    "division": Divisions.afcNorth,
    "name": "Steelers",
    "primaryColor": const Color(0xffffb612),
    "onPrimaryColor": const Color(0xff000000),
    "secondaryColor": const Color(0xff000000),
    "tertiaryColor": const Color(0xffa5acaf),
    "logo": "assets/logos/pittsburgh_steelers.png",
  },
  "sea": {
    "city": "Seattle",
    "division": Divisions.nfcWest,
    "name": "Seahawks",
    "primaryColor": const Color(0xff002244),
    "onPrimaryColor": const Color(0xff69be28),
    "secondaryColor": const Color(0xff69be28),
    "tertiaryColor": const Color(0xffa5acaf),
    "logo": "assets/logos/seattle_seahawks.png",
  },
  "sf": {
    "city": "San Francisco",
    "division": Divisions.nfcWest,
    "name": "49ers",
    "primaryColor": const Color(0xffaa0000),
    "onPrimaryColor": const Color(0xffb3995d),
    "secondaryColor": const Color(0xffb3995d),
    "logo": "assets/logos/san_francisco_49ers.png",
  },
  "was": {
    "city": "Washington",
    "division": Divisions.nfcEast,
    "name": "Commanders",
    "primaryColor": const Color(0xff5a1414),
    "onPrimaryColor": const Color(0xffffb612),
    "secondaryColor": const Color(0xffffb612),
    "logo": "assets/logos/washington_commanders.png",
  },
  "tb": {
    "city": "Tampa Bay",
    "division": Divisions.nfcSouth,
    "name": "Buccaneers",
    "primaryColor": const Color(0xffd50a0a),
    "onPrimaryColor": const Color(0xff34302b),
    "secondaryColor": const Color(0xffffffff),
    "tertiaryColor": const Color(0xff34302b),
    "logo": "assets/logos/tampa_bay_buccaneers.png",
  },
  "ten": {
    "city": "Tennessee",
    "division": Divisions.afcSouth,
    "name": "Titans",
    "primaryColor": const Color(0xff4b92db),
    "onPrimaryColor": const Color(0xff002244),
    "secondaryColor": const Color(0xff002244),
    "tertiaryColor": const Color(0xffa5acaf),
    "logo": "assets/logos/tennessee_titans.png",
  }
};
