name: cffp_web
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gsheets: ^0.5.0
  go_router: ^14.2.0
  hooks_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  morphable_shape: ^1.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logos/arizona_cardinals.png
    - assets/logos/atlanta_falcons.png
    - assets/logos/baltimore_ravens.png
    - assets/logos/buffalo_bills.png
    - assets/logos/carolina_panthers.png
    - assets/logos/chicago_bears.png
    - assets/logos/cincinnati_bengals.png
    - assets/logos/cleveland_browns.png
    - assets/logos/dallas_cowboys.png
    - assets/logos/denver_broncos.png
    - assets/logos/detroit_lions.png
    - assets/logos/green_bay_packers.png
    - assets/logos/houston_texans.png
    - assets/logos/indianapolis_colts.png
    - assets/logos/jacksonville_jaguars.png
    - assets/logos/kansas_city_chiefs.png
    - assets/logos/los_angeles_chargers.png
    - assets/logos/los_angeles_rams.png
    - assets/logos/las_vegas_raiders.png
    - assets/logos/miami_dolphins.png
    - assets/logos/minnesota_vikings.png
    - assets/logos/new_england_patriots.png
    - assets/logos/new_orleans_saints.png
    - assets/logos/new_york_giants.png
    - assets/logos/new_york_jets.png
    - assets/logos/philedelphia_eagles.png
    - assets/logos/pittsburgh_steelers.png
    - assets/logos/seattle_seahawks.png
    - assets/logos/san_francisco_49ers.png
    - assets/logos/washington_commanders.png
    - assets/logos/tampa_bay_buccaneers.png
    - assets/logos/tennessee_titans.png

  fonts:
    - family: Brother
      fonts:
        - asset: assets/fonts/Brother1816_Regular.otf
          weight: 400
    - family: Graduate
      fonts:
        - asset: assets/fonts/Graduate-Regular.ttf
          weight: 400
